project:
  type: website
  output-dir: docs

website:
  title: "Jaeyoung Yoon"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: travel.qmd
        text: Travel
      # - href: teaching.qmd
      #   text: Teaching
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/wodud1516

  page-footer:
    center: "© Jaeyoung Yoon"

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css